[package]
name = "halo2deeplearning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2022_08_19"}
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = "0.2.1" }
nalgebra = "0.31"
rand = "0.8"
mnist = "0.5"
ndarray = "0.15"
itertools = "0.10.3"
tensorflow = {version = "0.18.0", features = ["eager"], optional = true }
plotters = { version = "0.3.0", optional = true }
tract-onnx = { version = "0.17.7", optional = true }
anyhow = "1.0.65"
clap = { version = "4.0.7", features = ["derive"] }

[dev-dependencies]
criterion = {version = "0.3",  features = ["html_reports"]}


[[bench]]
name = "affine"
harness = false

[[bench]]
name = "cnvrl"
harness = false

[[bench]]
name = "relu"
harness = false


[features]
default = ["onnx"]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]
tensorflow = ["dep:tensorflow"]
onnx = ["dep:tract-onnx"]
