[target.x86_64-unknown-linux-musl]
image = "rustembedded/cross:x86_64-unknown-linux-musl"

[target.x86_64-apple-darwin]
image = "rustembedded/cross:x86_64-apple-darwin"

[target.aarch64-apple-darwin]
image = "rustembedded/cross:aarch64-apple-darwin"

[target.x86_64-pc-windows-msvc]
image = "rustembedded/cross:x86_64-pc-windows-msvc"
