name: Build and Publish EZKL Engine npm package

on:
  push:
    branches: ["test-releases"]
    paths-ignore:
      - "README.md"
      - "cla.md"
defaults:
  run:
    working-directory: .
jobs:
  publish-wasm-bindings:
    name: publish-wasm-bindings
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2024-02-06
          override: true
          components: rustfmt, clippy
      - uses: jetli/wasm-pack-action@v0.4.0
      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - name: Add rust-src
        run: rustup component add rust-src --toolchain nightly-2024-02-06-x86_64-unknown-linux-gnu
      - name: Install binaryen
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz | tar xzf -
          export PATH=$PATH:$PWD/binaryen-version_116/bin
          wasm-opt --version
      - name: Build wasm files for both web and nodejs compilation targets
        run: |
          wasm-pack build --release --target nodejs --out-dir ./pkg/nodejs . -- -Z build-std="panic_abort,std"
          wasm-pack build --release --target web --out-dir ./pkg/web . -- -Z build-std="panic_abort,std" --features web
      - name: Create package.json in pkg folder
        shell: bash
        run: |
          echo '{
            "name": "@ezkljs/engine",
            "version": "asd",
            "dependencies": {
              "@types/json-bigint": "^1.0.1",
              "json-bigint": "^1.0.0"
            },
            "files": [
              "nodejs/ezkl_bg.wasm",
              "nodejs/ezkl.js",
              "nodejs/ezkl.d.ts",
              "nodejs/package.json",
              "nodejs/utils.js",
              "web/ezkl_bg.wasm",
              "web/ezkl.js",
              "web/ezkl.d.ts",
              "web/snippets/wasm-bindgen-rayon-7afa899f36665473/src/workerHelpers.js",
              "web/package.json",
              "web/utils.js",
              "ezkl.d.ts"
            ],
            "main": "nodejs/ezkl.js",
            "module": "web/ezkl.js",
            "types": "nodejs/ezkl.d.ts",
            "sideEffects": [
              "web/snippets/*"
            ]
          }' > pkg/package.json
      # Additional steps omitted for brevity
      - name: Zip the entire package
        run: |
          zip -r pkg.zip ./pkg
      - name: Upload the zipped package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ezkl-engine-package
          path: pkg.zip
