name: FullProvingEVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:

  full-proving-evm-tests:

    runs-on: self-hosted
    timeout-minutes: 480
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Install solc
      run: (hash svm 2>/dev/null || cargo install svm-rs) && svm install 0.8.17 && solc --version
    - name: KZG full-prove tests (EVM)
      run: cargo test --release --verbose tests_evm::kzg_evm_fullprove_ -- --test-threads 3
