name: Large Tests
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Test scenario tags"
jobs:
  large-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03
          override: true
          components: rustfmt, clippy
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - name: efficientnet Mock
        run: cargo nextest --release --verbose tests::large_mock_::large_tests_3_expects --no-capture -- --include-ignored
      - name: efficientnet KZG prove and verify
        run: cargo nextest --release --verbose tests::large_kzg_prove_and_verify_::large_tests_3_expects --no-capture -- --include-ignored   
      - name: nanoGPT Mock
        run: cargo test --release --verbose tests::large_mock_::large_tests_1_expects --no-capture -- --include-ignored
      - name: nanoGPT KZG prove and verify
        run: cargo nextest --release --verbose tests::large_kzg_prove_and_verify_::large_tests_1_expects --no-capture -- --include-ignored
      - name: Self Attention Mock
        run: cargo nextest --release --verbose tests::large_mock_::large_tests_0_expects -- --include-ignored
      - name: Self Attention KZG prove and verify
        run: cargo nextest --release --verbose tests::large_kzg_prove_and_verify_::large_tests_0_expects --no-capture -- --include-ignored
      - name: mobilenet Mock
        run: cargo nextest --release --verbose tests::large_mock_::large_tests_2_expects --no-capture -- --include-ignored
      - name: mobilenet KZG prove and verify
        run: cargo nextest --release --verbose tests::large_kzg_prove_and_verify_::large_tests_2_expects --no-capture -- --include-ignored
