name: FullProvingEVM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:

  prove-and-verify-ipa-tests:

    runs-on: ubuntu-latest-16-cores
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: IPA prove and verify tests
      run: cargo test --release --verbose tests::ipa_prove_and_verify_ -- --test-threads 4

  prove-and-verify-kzg-tests:

    runs-on: ubuntu-latest-16-cores
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: KZG prove and verify tests
      run: cargo test --release --verbose tests::kzg_prove_and_verify_ -- --test-threads 2

