name: Build and Publish EZKL npm packages (wasm bindings and in-browser evm verifier)

on:
  push:
    branches: ["test-releases"]
    paths-ignore:
      - "README.md"
      - "cla.md"

defaults:
  run:
    working-directory: .
jobs:
  in-browser-evm-ver-publish:
    name: publish-in-browser-evm-verifier-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update version in package.json
        shell: bash
        run: |
          sed -i "s|\"version\": \".*\"|\"version\": \"asd\"|" in-browser-evm-verifier/package.json
      - name: Update @ezkljs/engine version in package.json
        shell: bash
        run: |
          sed -i "s|\"@ezkljs/engine\": \".*\"|\"@ezkljs/engine\": \"10.1.0\"|" in-browser-evm-verifier/package.json
      - name: Update the engine import in in-browser-evm-verifier to use @ezkljs/engine package instead of the local one;
        run: |
          sed -i "s|import { encodeVerifierCalldata } from '../nodejs/ezkl';|import { encodeVerifierCalldata } from '@ezkljs/engine';|" in-browser-evm-verifier/src/index.ts
      - name: Use pnpm 8
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          registry-url: "https://registry.npmjs.org"
      - name: Publish to npm
        run: |
          cd in-browser-evm-verifier
          pnpm install
          pnpm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Zip the package
        run: |
          cd in-browser-evm-verifier
          zip -r package.zip .
      - name: Upload package as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: in-browser-evm-verifier-package
          path: in-browser-evm-verifier/package.zip
