name: Build and Publish WASM<>JS Bindings

on:
  # Requires someone to trigger this build script via github workflows
  # It is required that the codebase is audited by contributors
  # before triggering to reduce the likelihood of supply chain attacks
  workflow_dispatch:

defaults:
  run:
    working-directory: .
jobs:
    wasm-publish:
        name: publish-wasm-bindings
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions-rs/toolchain@v1
            with:
              toolchain: nightly-2023-04-17
              override: true
              components: rustfmt, clippy
          - uses: jetli/wasm-pack-action@v0.4.0
          - name: Add wasm32-unknown-unknown target
            run: rustup target add wasm32-unknown-unknown
      
          - name: Install wasm-server-runner
            run: cargo install wasm-server-runner
        
          - name: Add rust-src
            run: rustup component add rust-src --toolchain nightly-2023-04-17-x86_64-unknown-linux-gnu
      
          - name: Build wasm files for both web and nodejs compilation targets
            run: |
                wasm-pack build --target web . -- -Z build-std="panic_abort,std" --features web
          - name: Create package.json in pkg folder
            shell: bash
            env:
                RELEASE_TAG: ${{ github.ref_name }}
            run: |
              echo '{
                "name": "@ezkljs/engine",
                "version": "${{ github.ref_name }}",
                "files": [
                  "ezkl_bg.wasm",
                  "ezkl.js",
                  "ezkl.d.ts",
                  "snippets/wasm-bindgen-rayon-7afa899f36665473/src/workerHelpers.js"
                ],
                "main": "ezkl.js",
                "types": "ezkl.d.ts",
                "sideEffects": [
                  "./snippets/*"
                ]
              }' > pkg/package.json

          - name: Set up Node.js
            uses: actions/setup-node@v3
            with:
              node-version: '18.12.1'
              registry-url: 'https://registry.npmjs.org'
  
          - name: Publish to npm
            run: |
              cd pkg
              npm install
              npm ci
              npm publish
            env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}